part of trust_wallet_core_ffi;

/// Chain identifiers for Ethereum-based blockchains, for convenience. Recommended to use the dynamic CoinType.ChainId() instead.
/// See also TWChainId.
abstract class TWEthereumChainID {
  static const int TWEthereumChainIDEthereum = 1;
  static const int TWEthereumChainIDClassic = 61;
  static const int TWEthereumChainIDRootstock = 30;
  static const int TWEthereumChainIDPoa = 99;
  static const int TWEthereumChainIDOpbnb = 204;
  static const int TWEthereumChainIDTfuelevm = 361;
  static const int TWEthereumChainIDVechain = 74;
  static const int TWEthereumChainIDCallisto = 820;
  static const int TWEthereumChainIDTomochain = 88;
  static const int TWEthereumChainIDPolygon = 137;
  static const int TWEthereumChainIDOkc = 66;
  static const int TWEthereumChainIDThundertoken = 108;
  static const int TWEthereumChainIDCfxevm = 1030;
  static const int TWEthereumChainIDGochain = 60;
  static const int TWEthereumChainIDBase = 8453;
  static const int TWEthereumChainIDMeter = 82;
  static const int TWEthereumChainIDCelo = 42220;
  static const int TWEthereumChainIDLinea = 59144;
  static const int TWEthereumChainIDScroll = 534353;
  static const int TWEthereumChainIDWanchain = 888;
  static const int TWEthereumChainIDGoerli = 5;
  static const int TWEthereumChainIDCronos = 25;
  static const int TWEthereumChainIDOptimism = 10;
  static const int TWEthereumChainIDXdai = 100;
  static const int TWEthereumChainIDSmartbch = 10000;
  static const int TWEthereumChainIDFantom = 250;
  static const int TWEthereumChainIDBoba = 288;
  static const int TWEthereumChainIDKcc = 321;
  static const int TWEthereumChainIDZksync = 324;
  static const int TWEthereumChainIDHeco = 128;
  static const int TWEthereumChainIDAcalaevm = 787;
  static const int TWEthereumChainIDMetis = 1088;
  static const int TWEthereumChainIDPolygonzkevm = 1101;
  static const int TWEthereumChainIDMoonbeam = 1284;
  static const int TWEthereumChainIDMoonriver = 1285;
  static const int TWEthereumChainIDRonin = 2020;
  static const int TWEthereumChainIDKavaevm = 2222;
  static const int TWEthereumChainIDMerlin = 4200;
  static const int TWEthereumChainIDIotexevm = 4689;
  static const int TWEthereumChainIDMantle = 5000;
  static const int TWEthereumChainIDMantletestnet = 5001;
  static const int TWEthereumChainIDMantlesepoliatestnet = 5003;
  static const int TWEthereumChainIDKlaytn = 8217;
  static const int TWEthereumChainIDAvalanchec = 43114;
  static const int TWEthereumChainIDEvmos = 9001;
  static const int TWEthereumChainIDBitgert = 32520;
  static const int TWEthereumChainIDArbitrumnova = 42170;
  static const int TWEthereumChainIDArbitrum = 42161;
  static const int TWEthereumChainIDAvalanchefujitestnet = 43113;
  static const int TWEthereumChainIDBitlayertestnet = 200810;
  static const int TWEthereumChainIDBitlayer = 200901;
  static const int TWEthereumChainIDTWCoinTypeHyperEVM = 999;
  static const int TWEthereumChainIDHyperEVMTestnet = 998;
  static const int TWEthereumChainIDMerlintestnet = 686868;
  static const int TWEthereumChainIDSepolia = 11155111;
  static const int TWEthereumChainIDSmartchain = 56;
  static const int TWEthereumChainIDBlast = 81457;
  static const int TWEthereumChainIDBlasttestnet = 168587773;
  static const int TWEthereumChainIDNeon = 245022934;
  static const int TWEthereumChainIDAurora = 1313161554;
}
